[project]
name = "bdgt"
version = "0.1.0"
description = "A Simple python cli app for budget management."
readme = "README.md"
authors = [
    { name = "ssannssarr", email = "ssantanusarkar8@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "asyncclick>=8.4.2.1",
    "rich>=15.0.0",
]

[project.scripts]
bdgt = "bdgt.cli"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
